%%
%% This file is part of the OpenGL binding generator for the BEAM.
%%
%% It resolves the "direct" OpenGL function (the one that have a 1:1 mapping),
%% with the help of the binding specs, to a data structure that can be used to
%% generate the binding.
%%
-module(direct_function_resolver).
-export([resolve/4]).

resolve(Functions, EnumTypes, BitfieldTypes, EnumToConstantMap) ->
    % Resolving a function consists of augmenting the existing "function data"
    % with more data.
    maps:fold(fun(Name, Data0, ResolvedFunctions) ->
        ResolvedFunctionData = resolve_function(
            Name,
            Data0,
            EnumTypes,
            BitfieldTypes,
            EnumToConstantMap
        ),
        Data1 = maps:merge(Data0, ResolvedFunctionData),
        maps:put(Name,  Data1, ResolvedFunctions)
    end, #{}, Functions).

resolve_function(
    _FunctionName,
    FunctionData,
    EnumTypes,
    BitfieldTypes,
    EnumToConstantMap
) ->
    case maps:get(direct_overloads, FunctionData, undefined) of
        undefined ->
            resolve_single_function(
                FunctionData,
                EnumTypes,
                BitfieldTypes,
                EnumToConstantMap
            );
        Overloads ->
            resolve_overloaded_function(
                FunctionData,
                Overloads,
                EnumTypes,
                BitfieldTypes,
                EnumToConstantMap
            )
    end.

resolve_single_function(
    FunctionData,
    EnumTypes,
    BitfieldTypes,
    EnumToConstantMap
) ->
    % There's never extra types generated by a direct function (it's only used
    % to combine multiple valid values commonly found in "indirect" functions).
    ExtraType = undefined,

    % We compute all data to generate the "-specs" attribute in the ".erl"
    % file.
    ParamsSpecs = maps:get(params_specs, FunctionData),
    ReturnSpecs = maps:get(return_specs, FunctionData),
    {SpecsParams, SpecsReturn} =
        common_specs_resolver:resolve_function_specs(ParamsSpecs, ReturnSpecs),

    % The number of parameters is the arity of the function.
    FunctionArity = length(SpecsParams),

    % In a "direct" function, there is always one function clause which calls
    % the associated NIF function (which wraps a given OpenGL command). It never
    % makes use of guards.
    FunctionClause = #{
        params => common_clauses_resolver:resolve_params(
            maps:get(params_specs, FunctionData),
            EnumTypes,
            BitfieldTypes,
            EnumToConstantMap
        ),
        guards => [],
        raw_function => maps:get(raw_function, FunctionData, maps:get(gl_command, FunctionData)),
        error_check => maps:get(error_check, FunctionData, true)
    },

    % Since it's a direct mapping, there is only one NIF function.
    GlCommand = maps:get(gl_command, FunctionData),
    NifName = maps:get(raw_function, FunctionData, GlCommand),
    {NifParams, NifReturn} = common_nifs_resolver:resolve_nif_function(
        maps:get(params_specs, FunctionData),
        maps:get(return_specs, FunctionData)
    ),
    NifArity = length(lists:filter(fun
        ({_, {out_scalar, _, _}}) -> false;
        ({_, {out_enum, _, _}}) -> false;
        ({_, {out_typed_value_list_from_counted_input, _, _, _}}) -> false;
        ({_, out_shader_precision_format}) -> false;
        (_) -> true
    end, NifParams)),

    NifFunctions = #{
        NifName => #{
            gl_command => GlCommand,
            arity => NifArity,
            params => NifParams,
            return => NifReturn
        }
    },

    #{
        extra_type => ExtraType,
        specs_params => SpecsParams,
        specs_return => SpecsReturn,
        function_arity => FunctionArity,
        function_clauses => [FunctionClause],
        nif_functions => NifFunctions
    }.

resolve_overloaded_function(
    FunctionData,
    Overloads,
    EnumTypes,
    BitfieldTypes,
    EnumToConstantMap
) ->
    ExtraType = undefined,
    {SpecsParams, SpecsReturn} = resolve_overloaded_function_specs(Overloads),
    FunctionArity = length(SpecsParams),
    GuardParam = direct_overload_guard_param(Overloads),
    FunctionClauses = lists:map(fun(Overload) ->
        resolve_overloaded_function_clause(
            Overload,
            GuardParam,
            EnumTypes,
            BitfieldTypes,
            EnumToConstantMap
        )
    end, Overloads),
    NifFunctions = lists:foldl(fun(Overload, Acc) ->
        maps:merge(Acc, resolve_overload_nif_function(Overload))
    end, #{}, Overloads),

    #{
        extra_type => ExtraType,
        specs_params => SpecsParams,
        specs_return => SpecsReturn,
        function_arity => FunctionArity,
        function_clauses => FunctionClauses,
        nif_functions => NifFunctions,
        gl_commands => maps:get(gl_commands, FunctionData)
    }.

resolve_overloaded_function_specs(Overloads) ->
    ResolvedSpecs = lists:map(fun(Overload) ->
        common_specs_resolver:resolve_function_specs(
            maps:get(params_specs, Overload),
            maps:get(return_specs, Overload)
        )
    end, Overloads),
    ParamsSpecs = [Params || {Params, _Return} <- ResolvedSpecs],
    ReturnSpecs = [Return || {_Params, Return} <- ResolvedSpecs],
    {merge_specs_params(ParamsSpecs), assert_same_specs_return(ReturnSpecs)}.

assert_same_specs_return([Return | Rest]) ->
    case lists:all(fun(Other) -> Other =:= Return end, Rest) of
        true ->
            Return;
        false ->
            erlang:error({incompatible_direct_overload_return_specs, [Return | Rest]})
    end.

merge_specs_params([Params | Rest]) ->
    lists:foldl(fun merge_specs_params_pair/2, Params, Rest).

merge_specs_params_pair(Params, Acc) ->
    lists:zipwith(fun({Name, SpecsA}, {Name, SpecsB}) ->
        {Name, merge_type_specs([SpecsA, SpecsB])};
    (ParamA, ParamB) ->
        erlang:error({incompatible_direct_overload_specs_params, ParamA, ParamB})
    end, Acc, Params).

merge_type_specs(TypeSpecs) ->
    Unique = sort_type_specs(dedupe_type_specs(lists:flatmap(fun
        ({set, TypeSpecsSet}) -> TypeSpecsSet;
        (TypeSpec) -> [TypeSpec]
    end, TypeSpecs))),
    case Unique of
        [TypeSpec] -> TypeSpec;
        _ -> {set, Unique}
    end.

dedupe_type_specs(TypeSpecs) ->
    lists:foldl(fun(TypeSpec, Acc) ->
        case lists:member(TypeSpec, Acc) of
            true -> Acc;
            false -> Acc ++ [TypeSpec]
        end
    end, [], TypeSpecs).

sort_type_specs(TypeSpecs) ->
    lists:sort(fun(A, B) ->
        type_specs_rank(A) =< type_specs_rank(B)
    end, TypeSpecs).

type_specs_rank({gl, int, []}) -> 10;
type_specs_rank({gl, float, []}) -> 20;
type_specs_rank(TypeSpec) when is_integer(TypeSpec) -> TypeSpec;
type_specs_rank(TypeSpec) -> {100, TypeSpec}.

direct_overload_guard_param(Overloads) ->
    ParamSpecs = [public_params(maps:get(params_specs, Overload)) || Overload <- Overloads],
    [FirstParams | RestParams] = ParamSpecs,
    DiffParams = lists:filtermap(fun(Index) ->
        [{in, Name, FirstType} | OtherParams] =
            [lists:nth(Index, Params) || Params <- [FirstParams | RestParams]],
        Types = [FirstType | [Type || {in, OtherName, Type} <- OtherParams, OtherName =:= Name]],
        case lists:all(fun(Type) -> Type =:= FirstType end, Types) of
            true ->
                false;
            false ->
                assert_supported_overload_guard_types(Types),
                {true, Name}
        end
    end, lists:seq(1, length(FirstParams))),
    case DiffParams of
        [GuardParam] ->
            GuardParam;
        _ ->
            erlang:error({unsupported_direct_overload_shape, Overloads})
    end.

public_params(ParamsSpecs) ->
    lists:filtermap(fun
        ({const, _Name, _Specs}) ->
            false;
        ({out, _Name, {gl_scalar, _StorageType, _ReturnType}}) ->
            false;
        ({out, _Name, {gl_enum, _Group}}) ->
            false;
        ({out, _Name, {gl_enum, _Group, _PublicName}}) ->
            false;
        ({out, _Name, {typed_value_list_from_counted_input, _SourceParam, _Type}}) ->
            false;
        ({out, _Name, {active_reflection_info, _TypeSpec}}) ->
            {true, {in, "MaxLength", gl_sizei}};
        ({out, _Name, {active_reflection_info, _SizeType, _TypeSpec}}) ->
            {true, {in, "MaxLength", gl_sizei}};
        ({Direction, Name, Specs}) ->
            {true, {Direction, Name, Specs}}
    end, ParamsSpecs).

assert_supported_overload_guard_types(Types) ->
    case lists:all(fun
        (gl_int) -> true;
        (gl_float) -> true;
        ({fixed_integer, Value}) when is_integer(Value) -> true;
        (_) -> false
    end, Types) of
        true ->
            ok;
        false ->
            erlang:error({unsupported_direct_overload_guard_types, Types})
    end.

resolve_overloaded_function_clause(
    Overload,
    GuardParam,
    EnumTypes,
    BitfieldTypes,
    EnumToConstantMap
) ->
    ParamsSpecs = maps:get(params_specs, Overload),
    #{
        guard_var => GuardParam,
        guards => overload_clause_guards(ParamsSpecs, GuardParam),
        params => common_clauses_resolver:resolve_params(
            ParamsSpecs,
            EnumTypes,
            BitfieldTypes,
            EnumToConstantMap
        ),
        raw_function => maps:get(raw_function, Overload, maps:get(gl_command, Overload)),
        error_check => maps:get(error_check, Overload, true)
    }.

overload_clause_guards(ParamsSpecs, GuardParam) ->
    Type = lists:foldl(fun
        ({in, GuardParam0, ParamType}, _Acc) when GuardParam0 =:= GuardParam ->
            ParamType;
        (_, Acc) ->
            Acc
    end, undefined, ParamsSpecs),
    case Type of
        gl_int -> [{is_integer, var}];
        gl_float -> [{is_float, var}];
        {fixed_integer, Value} when is_integer(Value) -> [{equals, var, Value}];
        _ -> erlang:error({unsupported_direct_overload_guard_type, GuardParam, Type})
    end.

resolve_overload_nif_function(Overload) ->
    GlCommand = maps:get(gl_command, Overload),
    NifName = maps:get(raw_function, Overload, GlCommand),
    {NifParams, NifReturn} = common_nifs_resolver:resolve_nif_function(
        maps:get(params_specs, Overload),
        maps:get(return_specs, Overload)
    ),
    NifArity = length(lists:filter(fun
        ({_, {out_scalar, _, _}}) -> false;
        ({_, {out_enum, _, _}}) -> false;
        ({_, {out_typed_value_list_from_counted_input, _, _, _}}) -> false;
        ({_, out_shader_precision_format}) -> false;
        (_) -> true
    end, NifParams)),
    #{
        NifName => #{
            gl_command => GlCommand,
            arity => NifArity,
            params => NifParams,
            return => NifReturn
        }
    }.
